version: '3.7'

services:
  app:
    build: .
    command: >
        gunicorn app.main:cors_app
        --bind 0.0.0.0:8000
        --access-logfile -
        --workers 2
        --worker-class uvicorn.workers.UvicornWorker
    ports:
      - "8000:8000"
    env_file:
      - .env
