services:
  - type: web
    name: xlwings-server
    runtime: docker
    repo: https://github.com/xlwings/xlwings-server
    plan: free
    envVars:
      - key: XLWINGS_LICENSE_KEY
        sync: false
    dockerContext: .
    dockerfilePath: ./Dockerfile
